"""
visualization.py
Member 4 - Validation & Visualization

Purpose:
    All plotting code for the project lives here. Every chart that
    goes into the final PPT is generated by a function in this file.

    Built in two stages, matching what data is actually available:
    STAGE 1 (built now): plots that only need M1's processed light
        curves and M2's BLS/folding output -- both already real and
        available.
    STAGE 2 (build once M3 delivers real output): plots that need
        M3's classification probabilities and trained model metrics.

Reads from:
    data/processed/TIC_{id}.npy -- M1's output
    results/candidates.csv -- M2's detect.py output
    results/folded_candidates.npy + results/candidate_ids.txt -- M2's fold.py output
    results/predictions.csv -- M3's predict.py output (Stage 2 functions only)
    results/metrics.json -- M3's evaluate output (Stage 2 functions only)

Output:
    results/plots/*.png

Usage:
    python visualization.py
    or
    from visualization.visualization import plot_raw_lightcurve, plot_folded_transit
"""

import os
import csv
import json
import numpy as np
import matplotlib.pyplot as plt

PROCESSED_DATA_DIR = "data/processed"
RESULTS_DIR = "results"
PLOTS_DIR = os.path.join(RESULTS_DIR, "plots")
CANDIDATES_PATH = os.path.join(RESULTS_DIR, "candidates.csv")
FOLDED_PATH = os.path.join(RESULTS_DIR, "folded_candidates.npy")
CANDIDATE_IDS_PATH = os.path.join(RESULTS_DIR, "candidate_ids.txt")
PREDICTIONS_PATH = os.path.join(RESULTS_DIR, "predictions.csv")
METRICS_PATH = os.path.join(RESULTS_DIR, "metrics.json")


def setup_style():
    """
    Sets consistent matplotlib styling for every plot in this project,
    so the whole PPT looks like it came from one coherent system rather
    than four different people's individual styles.

    Call this once at the top of any script that makes plots, before
    any plt.subplots() or plt.figure() call.
    """
    plt.rcParams["figure.dpi"] = 150
    plt.rcParams["font.size"] = 11
    plt.rcParams["axes.spines.top"] = False
    plt.rcParams["axes.spines.right"] = False
    plt.rcParams["figure.facecolor"] = "white"
    plt.rcParams["axes.facecolor"] = "white"
    plt.rcParams["axes.grid"] = True
    plt.rcParams["grid.alpha"] = 0.25


def load_folded_data():
    """
    Loads the folded candidates file, handling both the old format
    (plain numpy array, shape N x 200) and the new bundled format
    M3 requested (dict with tic_ids, fluxes, periods keys).

    Returns:
        tuple: (folded_matrix, candidate_ids, periods)
            folded_matrix: np.ndarray shape (N, 200)
            candidate_ids: list of str TIC IDs
            periods: np.ndarray shape (N,) or None if not available
    """
    if not os.path.exists(FOLDED_PATH):
        raise FileNotFoundError(
            "results/folded_candidates.npy not found. "
            "Run M2's fold.py (fold_all_candidates()) first."
        )

    raw = np.load(FOLDED_PATH, allow_pickle=True)

    # New bundled format: raw is a 0-d array containing a dict
    if raw.ndim == 0 and isinstance(raw.item(), dict):
        bundle = raw.item()
        folded_matrix = bundle["fluxes"]
        candidate_ids = list(bundle["tic_ids"])
        periods = bundle.get("periods", None)
        return folded_matrix, candidate_ids, periods

    # Old format: raw is a plain (N, 200) array, IDs from txt file
    folded_matrix = raw
    if not os.path.exists(CANDIDATE_IDS_PATH):
        raise FileNotFoundError(
            "results/candidate_ids.txt not found alongside the old-format "
            "folded_candidates.npy. Re-run fold_all_candidates() to regenerate."
        )
    with open(CANDIDATE_IDS_PATH, "r") as f:
        candidate_ids = f.read().strip().split("\n")
    return folded_matrix, candidate_ids, None


    """Loads M1's processed .npy file for a given TIC ID."""
    filepath = os.path.join(PROCESSED_DATA_DIR, f"TIC_{tic_id}.npy")
    data = np.load(filepath, allow_pickle=True).item()
    return data["time"], data["flux"]


def load_candidate_info(tic_id):
    """
    Looks up a candidate's BLS result (period, t0, power, depth,
    duration) from M2's results/candidates.csv.

    Returns:
        dict, or None if this TIC_ID is not in candidates.csv
    """
    if not os.path.exists(CANDIDATES_PATH):
        return None
    with open(CANDIDATES_PATH, "r") as f:
        reader = csv.DictReader(f)
        for row in reader:
            if row["TIC_ID"] == str(tic_id):
                return {
                    "period": float(row["period_days"]),
                    "power": float(row["power"]),
                    "depth": float(row["depth"]),
                    "duration": float(row["duration_days"]),
                    "t0": float(row["t0"]),
                }
    return None


def plot_raw_lightcurve(tic_id, save=True):
    """
    Plots a star's full raw (cleaned) light curve, with detected
    transit times marked as vertical dashed red lines if this star is
    a known candidate.

    Args:
        tic_id (str): TIC ID of the star to plot
        save (bool): if True, saves to results/plots/lc_raw_{tic_id}.png

    Returns:
        matplotlib Figure object
    """
    setup_style()
    time, flux = load_processed_star(tic_id)
    candidate_info = load_candidate_info(tic_id)

    fig, ax = plt.subplots(figsize=(12, 4))
    ax.plot(time, flux, "k.", markersize=1.5, alpha=0.5)

    title = f"TIC {tic_id}"
    if candidate_info is not None:
        period = candidate_info["period"]
        t0 = candidate_info["t0"]
        # Mark every predicted transit time across the observation span
        transit_time = t0
        while transit_time < time.max():
            if transit_time >= time.min():
                ax.axvline(transit_time, color="#d62728", alpha=0.4, linestyle="--")
            transit_time += period
        title += f" — Period: {period:.3f} days"

    ax.set_xlabel("Time (BTJD)")
    ax.set_ylabel("Normalized flux")
    ax.set_title(title)
    plt.tight_layout()

    if save:
        os.makedirs(PLOTS_DIR, exist_ok=True)
        out_path = os.path.join(PLOTS_DIR, f"lc_raw_{tic_id}.png")
        plt.savefig(out_path, dpi=150)
        print(f"Saved {out_path}")

    return fig


def plot_folded_transit(tic_id, save=True):
    """
    Plots a candidate's phase-folded transit shape -- all individual
    dips overlaid into one clean averaged shape, the same array M3's
    CNN actually classifies.

    Args:
        tic_id (str): TIC ID, must be present in
            results/candidate_ids.txt (i.e. must have been folded by
            M2's fold.py)
        save (bool): if True, saves to results/plots/lc_folded_{tic_id}.png

    Returns:
        matplotlib Figure object
    """
    setup_style()

    folded_matrix, candidate_ids, periods = load_folded_data()

    if str(tic_id) not in candidate_ids:
        raise ValueError(
            f"TIC {tic_id} not found in folded candidates. This star may "
            f"not have passed detect.py's candidate threshold, or fold.py "
            f"hasn't been run on it yet."
        )

    row_idx = candidate_ids.index(str(tic_id))
    folded_flux = folded_matrix[row_idx]
    phase = np.linspace(-0.5, 0.5, len(folded_flux))

    fig, ax = plt.subplots(figsize=(8, 5))
    ax.plot(phase, folded_flux, linewidth=1.2, color="#1f77b4")
    ax.axhline(1.0, color="gray", linestyle="--", alpha=0.5, linewidth=0.8)

    candidate_info = load_candidate_info(tic_id)
    title = f"TIC {tic_id} — Phase-folded transit"
    if candidate_info is not None:
        title += f"\nDepth: {candidate_info['depth']*100:.3f}% | Duration: {candidate_info['duration']*24:.2f}hr"

    ax.set_xlabel("Phase")
    ax.set_ylabel("Normalized flux")
    ax.set_title(title)
    plt.tight_layout()

    if save:
        os.makedirs(PLOTS_DIR, exist_ok=True)
        out_path = os.path.join(PLOTS_DIR, f"lc_folded_{tic_id}.png")
        plt.savefig(out_path, dpi=150)
        print(f"Saved {out_path}")

    return fig


def plot_all_candidates_grid(save=True):
    """
    Plots every candidate's folded transit shape in one grid image, for
    quick visual comparison across all candidates at once -- useful for
    manually screening which candidates look like real transits versus
    noise or eclipsing binaries before relying on M3's classifier.

    Args:
        save (bool): if True, saves to results/plots/all_candidates_grid.png

    Returns:
        matplotlib Figure object
    """
    setup_style()

    folded_matrix, candidate_ids, periods = load_folded_data()

    n = len(candidate_ids)
    n_cols = 5
    n_rows = int(np.ceil(n / n_cols))

    fig, axes = plt.subplots(n_rows, n_cols, figsize=(3.5 * n_cols, 2.8 * n_rows))
    axes = np.array(axes).flatten()

    for i, tic_id in enumerate(candidate_ids):
        ax = axes[i]
        ax.plot(folded_matrix[i], linewidth=0.8, color="#1f77b4")
        ax.set_title(f"TIC {tic_id}", fontsize=9)
        ax.set_xticks([])
        ax.set_yticks([])

    for j in range(n, len(axes)):
        axes[j].axis("off")

    plt.tight_layout()

    if save:
        os.makedirs(PLOTS_DIR, exist_ok=True)
        out_path = os.path.join(PLOTS_DIR, "all_candidates_grid.png")
        plt.savefig(out_path, dpi=120)
        print(f"Saved {out_path}")

    return fig


# ---------------------------------------------------------------------
# STAGE 2 -- the following functions need M3's real output to run.
# They are included now so the file is complete, but should be TESTED
# against real data once M3 delivers results/predictions.csv and
# results/metrics.json -- testing against synthetic stand-ins for
# these specific functions is lower priority since M3's actual output
# format may need small adjustments once it exists for real.
# ---------------------------------------------------------------------

def plot_confidence(tic_id, save=True):
    """
    Plots a horizontal bar chart of a candidate's classification
    confidence across all 4 classes (planet, eclipsing_binary, blend,
    other), from M3's results/predictions.csv.

    Args:
        tic_id (str): TIC ID to plot
        save (bool): if True, saves to results/plots/confidence_{tic_id}.png

    Returns:
        matplotlib Figure object
    """
    setup_style()

    if not os.path.exists(PREDICTIONS_PATH):
        raise FileNotFoundError(
            "results/predictions.csv not found. Run M3's predict.py first."
        )

    row = None
    with open(PREDICTIONS_PATH, "r") as f:
        reader = csv.DictReader(f)
        for r in reader:
            if r["TIC_ID"] == str(tic_id):
                row = r
                break

    if row is None:
        raise ValueError(f"TIC {tic_id} not found in predictions.csv")

    classes = ["planet", "binary", "blend", "other"]
    probs = [
        float(row.get("planet_prob", 0)),
        float(row.get("binary_prob", 0)),
        float(row.get("blend_prob", 0)),
        float(row.get("other_prob", 0)),
    ]
    colors = ["#2ecc71" if c == "planet" else "#95a5a6" for c in classes]

    fig, ax = plt.subplots(figsize=(7, 3.5))
    ax.barh(classes, probs, color=colors)
    ax.set_xlim(0, 1)
    ax.set_xlabel("Confidence")

    predicted = row.get("predicted_class", "unknown")
    max_prob = max(probs)
    ax.set_title(f"TIC {tic_id} — Classification: {predicted} ({max_prob*100:.0f}% confidence)")

    for i, p in enumerate(probs):
        ax.text(p + 0.02, i, f"{p*100:.0f}%", va="center", fontsize=10)

    plt.tight_layout()

    if save:
        os.makedirs(PLOTS_DIR, exist_ok=True)
        out_path = os.path.join(PLOTS_DIR, f"confidence_{tic_id}.png")
        plt.savefig(out_path, dpi=150)
        print(f"Saved {out_path}")

    return fig


def plot_confusion_matrix(save=True):
    """
    Plots the model's confusion matrix from M3's results/metrics.json
    -- a heatmap showing how often the CNN's predictions matched the
    true labels on the test set.

    Args:
        save (bool): if True, saves to results/plots/confusion_matrix.png

    Returns:
        matplotlib Figure object
    """
    setup_style()
    import seaborn as sns

    if not os.path.exists(METRICS_PATH):
        raise FileNotFoundError(
            "results/metrics.json not found. Run M3's evaluate_on_test_set() first."
        )

    with open(METRICS_PATH, "r") as f:
        metrics = json.load(f)

    if "confusion_matrix" not in metrics:
        raise KeyError(
            "metrics.json does not contain a 'confusion_matrix' key. "
            "Check M3's evaluate_on_test_set() output format matches "
            "what this function expects."
        )

    cm = np.array(metrics["confusion_matrix"])
    labels = ["Planet", "Binary", "Blend", "Other"]

    fig, ax = plt.subplots(figsize=(6, 5))
    sns.heatmap(cm, annot=True, fmt="d", cmap="Greens",
                xticklabels=labels, yticklabels=labels, ax=ax)
    ax.set_xlabel("Predicted class")
    ax.set_ylabel("True class")
    ax.set_title("Model classification results (test set)")
    plt.tight_layout()

    if save:
        os.makedirs(PLOTS_DIR, exist_ok=True)
        out_path = os.path.join(PLOTS_DIR, "confusion_matrix.png")
        plt.savefig(out_path, dpi=150)
        print(f"Saved {out_path}")

    return fig


def plot_all(top_n=3):
    """
    Convenience function: plots raw + folded views for the top N
    candidates (by BLS power score), plus the full candidates grid.
    Stage 2 plots (confidence, confusion matrix) are skipped
    automatically if M3's output doesn't exist yet.

    Args:
        top_n (int): how many top candidates to plot in detail
    """
    if not os.path.exists(CANDIDATES_PATH):
        print("No candidates.csv found. Run M2's detect.py first.")
        return

    with open(CANDIDATES_PATH, "r") as f:
        reader = csv.DictReader(f)
        candidates = list(reader)

    candidates_sorted = sorted(candidates, key=lambda r: float(r["power"]), reverse=True)
    top_candidates = candidates_sorted[:top_n]

    for c in top_candidates:
        tic_id = c["TIC_ID"]
        try:
            plot_raw_lightcurve(tic_id)
            plot_folded_transit(tic_id)
        except Exception as e:
            print(f"Could not plot TIC {tic_id}: {e}")

    try:
        plot_all_candidates_grid()
    except Exception as e:
        print(f"Could not plot candidates grid: {e}")

    if os.path.exists(PREDICTIONS_PATH):
        for c in top_candidates:
            try:
                plot_confidence(c["TIC_ID"])
            except Exception as e:
                print(f"Could not plot confidence for TIC {c['TIC_ID']}: {e}")
    else:
        print("Skipping confidence plots -- predictions.csv not yet available (waiting on M3)")

    if os.path.exists(METRICS_PATH):
        try:
            plot_confusion_matrix()
        except Exception as e:
            print(f"Could not plot confusion matrix: {e}")
    else:
        print("Skipping confusion matrix -- metrics.json not yet available (waiting on M3)")


if __name__ == "__main__":
    plot_all()
